### ISSUE TITLE
When there are many cadastred users, only 10 of then is shown

### ISSUE THREAD

**Issue by gleisonsilva** [Activiti/Activiti-AngularApp#2]
Only the first 10 users is show, even when there are much more users in activiti database (and they can be viewed using Activity Explorer)...

**Comment by gleisonsilva** [comment]
As a workaround, I've changed the line above in scripts/factory/userService.js:

from
```
var data = $resource('/service/identity/users/:user', {user: "@user"});
```
to
```
var data = $resource('/service/identity/users/:user', {user: "@user", size: 100});
```

**Comment by savicprvoslav** [comment]
Hello, 
 thanks.
