### ISSUE TITLE
Login form

### ISSUE THREAD

**Issue by narenphp** [Activiti/Activiti-AngularApp#3]
Hi,

Please changes password label from User Name to Password.

**Comment by narenphp** [comment]
![screenshot from 2015-04-06 20 32 39](https://cloud.githubusercontent.com/assets/311678/7006134/57ba22b2-dc9c-11e4-83fa-6c0730d59d9d.png)

**Comment by narenphp** [comment]
Please, see the above attached snap.

**Comment by savicprvoslav** [comment]
Hello, 
fixed.
