### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by mathiaslin** [Activiti/Activiti-AngularApp#5]
The demo as documented

> http://activiti.alfrescoblog.com/ u/p activiti/activiti

does not work. Trying to login opens another "Authentication Required. The server http://activiti.alfrescoblog.com:8080 requires a username and password. The server says: Realm" dialog; and u/p activiti/activiti" does not work there. (Chrome Browser)

**Comment by savicprvoslav** [comment]
Hi, 
 some people like to delete all users from the system :). You can login now , thank you for reporting.

**Comment by antetna** [comment]
It looks like something is broken again:

Request URL: 	http://activiti.alfrescoblog.com/service/identity/users/activiti
Request Method: 	GET
Status Code: 	HTTP/1.1 401 Unauthorized

HTTP Status 401 - Authentication failed for this username and password
type Status report
message Authentication failed for this username and password
description This request requires HTTP authentication.
Apache Tomcat/7.0.52 (Ubuntu)

**Comment by savicprvoslav** [comment]
Hi, 
 like I have said people remove all users and all groups (facepalm). 

I have created few users not so that you can try.

Thank you for letting me know that login does not work.

**Comment by testn** [comment]
sorry but it does not work again.

**Comment by savicprvoslav** [comment]
Thanks, it works now!
