### ISSUE TITLE
Local Deployment Strategy

### ISSUE THREAD

**Issue by xsalefter** [Activiti/Activiti-AngularApp#7]
Hi,

I tried to run this application locally. I have activiti-explorer and activiti-rest deployed in tomcat. So far, I'm able to use grunt and run application, but I can't login. Error from browser log showing this message:

> GET http://localhost:9000/service/identity/users/kermit?size=100 404 (Not Found)

I understand that this is because the REST API run in the different server so no way we able to get data from http://localhost:9000/service/ . Furthermore, I see that there's UserService code that invoke something like:

> var data = $resource('/service/identity/users/:user', {user: "@user", size: 100});

Don't you think that we need to change this to:

> var data = $resource(externalizedRestRootURL + '/service/identity/users/:user', {user: "@user", size: 100});

or something like that? Did I miss something here? What is your approach and suggestion to run this locally? Thanks for your answer.

**Comment by savicprvoslav** [comment]
Hello, 
 you missed the part where you need to setup a apache httpd url_proxy , here is the link https://github.com/Activiti/Activiti-AngularApp#how-to-connect-activiti-rest-with-angular-and-not-have-cross-origin-problem 

Basically idea is that :
- apache httpd is on port 80
- grunt is on port 9000
- activiti tomcat is on port 8080

Then url_proxy proxies the http requests
-  from http://localhost/service to http://localhost:8080/activiti-rest/service 
-  http://localhost to http://localhost:9000/

And finally you access your application on http://localhost . I hope that you do not find this to difficult to handle as you has all explained on github, alfrescoblog.com and also you have online tutorials that handle this use case quite well using other webservers .

Let me know if you are able to arrange this setup.

**Comment by xsalefter** [comment]
Hi @savicprvoslav Thanks for your answer. Of course it is works with apache httpd url_proxy, but it broke other apps I try to develop in my local machine.. :smile: . Well, I guess the whole idea is running all of this inside docker container?

Another question is, why we have pom.xml of this project? Do you planning that in the future there's will be java/server side code involved?

Thanks,
Resa

**Comment by savicprvoslav** [comment]
Activiti project had angular app with lets say few features, I extended it to this point but kept original I guess maven project.

Since this is an angular app it is more then easy to put it together under standard grunt workflow.

Tx
