### ISSUE TITLE
Demo login does not work

### ISSUE THREAD

**Issue by ykhadilkar** [Activiti/Activiti-AngularApp#9]
The demo as documented
http://activiti.alfrescoblog.com/ u/p activiti/activiti does not work. Trying to login opens another "Authentication Required. The server http://activiti.alfrescoblog.com:8080 requires a username and password.
<img width="1141" alt="screen shot 2016-12-27 at 1 15 55 am" src="https://cloud.githubusercontent.com/assets/3237208/21492368/1b02b588-cbd2-11e6-9b2a-51447c8bcb36.png">

What is the username / password for second auth?

**Comment by ykhadilkar** [comment]
After looking at closed issues, it seems like someone deleted sample users. Quick tip though, username and password for second auth is same as first login.

**Comment by savicprvoslav** [comment]
Database is reverted.

Thank you.
